"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _about_content from './about-content.bones.json'
import _research_content from './research-content.bones.json'
import _publications_content from './publications-content.bones.json'
import _achievements_content from './achievements-content.bones.json'
import _writings_content from './writings-content.bones.json'
import _contact_content from './contact-content.bones.json'
import _courses_content from './courses-content.bones.json'
import _workshops_content from './workshops-content.bones.json'
import _projects_content from './projects-content.bones.json'
import _affiliations_content from './affiliations-content.bones.json'
import _volunteering_content from './volunteering-content.bones.json'
import _invited_talks_content from './invited-talks-content.bones.json'
import _user_profile_card from './user-profile-card.bones.json'

registerBones({
  "about-content": _about_content,
  "research-content": _research_content,
  "publications-content": _publications_content,
  "achievements-content": _achievements_content,
  "writings-content": _writings_content,
  "contact-content": _contact_content,
  "courses-content": _courses_content,
  "workshops-content": _workshops_content,
  "projects-content": _projects_content,
  "affiliations-content": _affiliations_content,
  "volunteering-content": _volunteering_content,
  "invited-talks-content": _invited_talks_content,
  "user-profile-card": _user_profile_card,
})
