"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _home_projects_section from './home-projects-section.bones.json'
import _home_hero_section from './home-hero-section.bones.json'
import _about_hero_section from './about-hero-section.bones.json'
import _about_details_section from './about-details-section.bones.json'
import _research_content from './research-content.bones.json'
import _publications_content from './publications-content.bones.json'
import _achievements_content from './achievements-content.bones.json'
import _writings_content from './writings-content.bones.json'
import _contact_content from './contact-content.bones.json'
import _courses_content from './courses-content.bones.json'
import _workshops_content from './workshops-content.bones.json'
import _projects_content from './projects-content.bones.json'
import _affiliations_content from './affiliations-content.bones.json'
import _volunteering_content from './volunteering-content.bones.json'
import _invited_talks_content from './invited-talks-content.bones.json'

configureBoneyard({"color":"#e0e0e0","animate":"pulse"})

registerBones({
  "home-projects-section": _home_projects_section,
  "home-hero-section": _home_hero_section,
  "about-hero-section": _about_hero_section,
  "about-details-section": _about_details_section,
  "research-content": _research_content,
  "publications-content": _publications_content,
  "achievements-content": _achievements_content,
  "writings-content": _writings_content,
  "contact-content": _contact_content,
  "courses-content": _courses_content,
  "workshops-content": _workshops_content,
  "projects-content": _projects_content,
  "affiliations-content": _affiliations_content,
  "volunteering-content": _volunteering_content,
  "invited-talks-content": _invited_talks_content,
})
